### ISSUE TITLE
Use arrows to move

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#101]
Hi @tblanke 

W.r.t. a grid layout of inputs (e.g. the monthly loads within GHEtool), it would be more logical if the arrows up and down would correspond to moving to, respectively, the higher and lower cell.

I do not think that this should be default behaviour, but if we are going to create a grid layout, then to me it seems a good idea to have this option.

Best
@wouterpeere

**Comment by tblanke** [comment]
It is implemented in issue #143.
