### ISSUE TITLE
Wrong value in ButtonBox

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#104]
Hi @tblanke 

I noticed a small bug in the ButtonBox option.

To reproduce:

1. Delete backup
2. Run the GUI
3. Press 'a' (the selected option) of the ButtonBox: 'a or b or c?'
4. You get a warning of a wrong value (the check_value() function of the button box returns -1)
5. Press 'a' again --> now no error since it was not selected.

This error also occurs when the toggle behaviour is dissabled.

Best,
@wouterpeere

**Comment by wouterpeere** [comment]
After some debugging, I think this is due since the activating/deactivating of a button in the ButtonBox happens first, then the check_value() function is called after which the update_function() of the ButtonBox is called (which handles the activation/deactivation of the buttons within the ButtonBox).

**Comment by tblanke** [comment]
Hi @wouterpeere ,

That is correct. I have changed the toggled event to a clicked event. This change solves the issue.

With best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

I will take a look. I'm wondering if this will cause any problems if the ButtonBox is linked to the visibility of another option. E.g. if you change from one scenario to the next, the selected option in the ButtonBox might change, which would call the toggled event but not the clicked event. Not sure if that would cause any further bugs ...


Best,
@wouterpeere

**Comment by wouterpeere** [comment]
Hi @tblanke 

W.r.t. the previous comment: the linked_options seem to be still checked by the toggled event. I assume everythings is working as expected.

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I have also about if this can cause any problems, but I did not see anything. So I would stay with the toggle behaviour.

With best regards
@tblanke
