### ISSUE TITLE
FlexibleAmount is broken

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#108]
Hi @tblanke 

I noticed that the FlexibleAmount option is totally broken (strange that this slipped through the tests).
It is no longer possible to add a new row 'TypeError: FlexibleAmount._add_entry_at_row() got multiple values for argument 'row'
or remove one: 'TypeError: FlexibleAmount._del_entry() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given'

Best,
@wouterpeere

**Comment by wouterpeere** [comment]
Hi @tblanke 

I solved this.
I just need to implement a test to check for this.

I also noticed another bug w.r.t. FlexibleAmount. If you try to remove the last row, this does not work (of course), but part of the gui is frozen, since it thinks this is a 'wrong value', which is not ...

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I will fix the second thing.

With best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

I just did that 😄 

Best,
@wouterpeere
