### ISSUE TITLE
show_option_under_multiple_conditions on result page

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#121]
Hi @tblanke 

The show_option_under_multiple_conditions is not working for options on the result page.
I think this is due to the fact that it only checks for add_link_2_show_options but not those connected via the new show_option_under_multiple_conditions option ..

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I think I have fixed your issue. Can you please have a look and ensure, that the option you would like to display is not used under a add_link_2_show function?

Kind regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

Seems fine to me.

I will continue with some more thorough testing later this week.

Best,
@wouterpeere
