### ISSUE TITLE
Strange issue with autosaving

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#128]
Hi @tblanke 

I found a strange behaviour with autosaving enabled. To reproduce:
1) Delete backup
2) Open ScenarioGUI
3) Go to settings and enable autosaving
4) Press 2x add scenario
5) Calculate all scenario's
6) Go to scenario 1 and click on the first page
7) Change the listbox option and e.g. 'a or b or c' to b
8) Press calculate current cenario
9) Save the file and close ScenarioGUI
10) Reopen ScenarioGUI and all the changes will be gone

Best,
@wouterpeere

**Comment by wouterpeere** [comment]
Hi @tblanke 

Another (or perhaps the same?) error is reproduced like this:
1) Delete backup
2) Open ScenarioGUI
3) Enable autosaving
4) Run scenario --> the result is 102m
5) Set int_A to 5
6) Run scenario --> the result is still 102m ...

I created a test file to illustrate this (second) error.

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I have implemented a test and fixed it. Can you please verfiy that it also works for you?

Kind regards
@tblanke

**Comment by wouterpeere** [comment]
This seems to work!
I will continue tomorrow for checking it with GHEtool as well ...
