### ISSUE TITLE
Change_scenario is not working properly with multiple_scenario_calculation

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#131]
Hi @tblanke 

I noticed another bug (see test_run_multiple_scenarios).
When you create a couple of scenarios, you run start_multiple_scenarios_calculation(), and then use change_scenario(0) to go back to the first scenario, the result-object is still that of the last scenario ...

In the GUI itself it works, so perhaps it is only something in the test-case.

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I would like to postphone this to v0.3.1, because this is a bigger thing. The items are link to the scenario list widget. 
If you would like to trigger this use main_window.list_widget_scenario.setCurrentItem(main_window.list_widget_scenario.item(0)).

Kind regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

This will do the trick.
I will implement it in my tests, and do a file check of the behaviour of ScenarioGUI.

Best,
@wouterpeere
