### ISSUE TITLE
Version can not be found error 

### ISSUE THREAD

**Issue by tblanke** [tblanke/ScenarioGUI#134]
The Version check in from the global settings can not be found or the section with the version can not exists in the current setup.cfg file.

**Comment by wouterpeere** [comment]
Hi @tblanke 

Is it an idea to decouple the version in the setup.cfg with the version of the GUI?
In that way, we can put the version inside the gui_config.ini, where (in my opinion), it belongs?

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I have implemented an approach that first checks if a version number exits in the gui_config file and otherwise checks the setup.cfg file. What do you think about this solution?

With best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

I think this is perfect!

Best,
@wouterpeere
