### ISSUE TITLE
Hint & tooltip

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#137]
Hi @tblanke 

As discussed, it would be interesting to have a tooltip/hint option for the Options.

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I have implemented an approach for this. Can you please have a look?
You can set a tool tip using set_tool_tip
There is currently a Bug in Qt6.5.2 (QToolTip StyleSheet Color Property Broken in 6.5.2) why the text color is not set. So do not worry about this.
Currently there is no way of translating it. What do you thing about the idea of making the set_tool_tip input optionally a list of translation. Which can then be captured from the translation class?

Kind regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

I think an optional list for translations is perfect.
I will take a look at this tomorrow, I hope, I have to finish some work still today ...

Best,
@wouterpeere

**Comment by wouterpeere** [comment]
Hi @tblanke 

I really like this! Looks perfect to me!


Best,
@wouterpeere
