### ISSUE TITLE
Start with one scenario

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#145]
Hi @tblanke 

One other small thing I noticed: when opening the gui first, there are no scenarios. This is strange, since there is data anyways. Also, if you have multiple scenarios, you cannot delete them all.

So basicly, the initial situation, is rather strange and unwanted. I would suggest starting with 'Scenario 1' always instead of starting with 0 scenarios and only adding the first when the scenario is calculated, saved ...

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

This is in progress.

Kind regards
@tblanke
