### ISSUE TITLE
Bug in saving ListBox values

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#154]
Hi @tblanke 

It looks like I finally could trace a bug down w.r.t. the ListBox values.
If you add new scenario's, the values do not always get saved, leading to unexpected and hard to find bugs ...

To reproduce:
1) Delete backup
2) Open ScenarioGUI
3) Change the value of the Listbox to e.g. c3
4) Save the project and close ScenarioGUI
5) Open ScenarioGUI --> Listbox is still c3
6) Add new scenario
7) Save project & close
8) Reopen ScenarioGUI --> Listbox is a1!

When I look into the backup file, I see that it does not save the values for the Listbox in the json for the first scenario ...

Best,
@wouterpeere

**Comment by wouterpeere** [comment]
Hi @tblanke 

I think I found a solution for this bug, but it seems rather strange.
Can you take a look?

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

Your solution works. I have implemented a test for it.

With best regards
@tblanke
