### ISSUE TITLE
Saving on closing does not save the document

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#157]
Hi @tblanke 

I noticed that if you try to save ScenarioGUI with changes, it prompts a warning asking if you would like to save the changes. If you select to save the changes, it only saves them to the backup, not to the project itself.

Best,
@wouterpeere

**Comment by wouterpeere** [comment]
Hi @tblanke 

This error is not consistent. I think it has something to do with the fact that saving is now in a separate thread and if it takes a while to save a file, the program is already closed, killing the thread. Can this be the case?

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

Indeed you are correct with the threads. I already have a solution. I am just creating the tests.

Kind regards
@tblanke

**Comment by tblanke** [comment]
Hi @wouterpeere ,
I have implemented a solution. Can you please have a look if it works for you?
Kind regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

I can confirm!

Best,
@wouterpeere
