### ISSUE TITLE
Open file whilst current file is not saved

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#159]
Hi @tblanke 

I also noticed another small bug.
If you change a file, it is possible to open a new one, without a 'do you want to save the changes' message. It is also possible to create a new document whilst there are unsaved changes. This can lead to loss of data.

Best,
@wouterpeere

**Comment by wouterpeere** [comment]
Hi @tblanke 

I will propose a solution for this.

**Comment by wouterpeere** [comment]
Hi @tblanke 

Can you please take a look at the solution? Does it work for you?

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I will take a look soon.

Kind regards
@tblanke

**Comment by tblanke** [comment]
Hi @wouterpeere,

I am fine with your approach. The thing I have changed is that the dialog is now split into a close dialog and a continue dialog. Which is mainly different in its text. Also I have implemented a test. Can you please have a look if that new dialog is also fine for you?

Kind regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

Terminology is perfect for me!

Just one thing I noticed. When you press 'continue', the new project you opened is also seen as 'changed', so perhaps we have to reset the changedFile flag?

Best,
@wouterpeere
