### ISSUE TITLE
store matplotlib figure in json?

### ISSUE THREAD

**Issue by tblanke** [tblanke/ScenarioGUI#30]

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I have not found a way to store figure in json format. I think the way implemented in GHEtool is the better solution.

**Comment by wouterpeere** [comment]
I honestly also don't see any way of how we can tackle this in an easy manner. I think we better keep it the way it is.

@tblanke , you may this issue from my part.

Best,
@wouterpeere
