### ISSUE TITLE
Scenario buttons not resizing

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#42]
Hi @tblanke 

I noticed that, whenever one puts in a long scenario name, the buttons above do not resize as espected.
![image](https://user-images.githubusercontent.com/52632307/233315515-b0a41463-b233-4d51-a508-ca596fd92d97.png)

Perhaps this issue is already solved in ScenarioGUI, but I noticed it in GHEtool v2.1.2.

Best,
Wouter

**Comment by tblanke** [comment]
This is indeed a bug. I will create a fix.
