### ISSUE TITLE
add_link_2_show: disable options

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#46]
Hi @tblanke 

Right now, the visibility of options is determined by using the add_link_2_show function. However, referring to GHEtool, we have three sizing methods: L2, L3 and L4. Imagine I would add an option that is compatible with L3 and L4, I would have to duplicate this option, give it another name and make the add_link_2_show functions so that whenever this new option is checked, I switch over to the ButtonBox with only L3 and L4 instead of the one with L2, L3 and L4.

It would be nice to implement a function so that one can simply disable one button (if there are more than two).

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I will take a look at it.

With best regards
@tblanke

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I have implemtned a first draft in the corresponding branch.

**Comment by tblanke** [comment]
Hi @wouterpeere ,

Can you take a look at the first draft?

**Comment by tblanke** [comment]
Hi @wouterpeere ,

What do you think about the first draft?

**Comment by wouterpeere** [comment]
Hi @tblanke 

Sorry, I forgot about this! I will take a look at it ASAP.

**Comment by wouterpeere** [comment]
I noticed some buggy behaviour (some of which is also present in v0.2.2 in noticed now).
These bugs can be replicated using the last update in the branch (the merging with the main branch).

**Bug 1**
1. Delete backup
2. Open the GUI
3. Filenamebox is hidden (which is correct, since it depends on the aim-page and the index=1 of the button box ('b'))
4. Click on substract
5. Click on add again
6. --> filenamebox is shown (which is wrong)

**Bug 2**
1. Delete backup
2. Open the GUI
3. Filenamebox is hidden (which is correct, since it depends on the aim-page and the index=1 of the button box ('b'))
4. Click on substract
5. Click on 'b' in the buttonbox
6. The filenamebox is visible (although not on the aim add page!)

**Bug 3**
1. Delete backup
2. Open the GUI
3. Select 'b' in the button box (this opens the filenamebox which is now correct)
4. Set floatinputbox to 49, so option b is disabled in the buttonbox
5. Filenamebox is still visible

**Bug 4**
1. Delete backup
2. Open GUI
3. Click on substract
4. Textbox 'only visible on add' is hidden (correct)
5. Increment a above 5 so the subtract aim is disabled
6. 'only visible on add' is still hidden (incorrect)

--> I think bug 3/4 has something to do with the difference between 'setEnabled' and 'Click' in the dissable function you created. Although bug 4 is related to the linked options of the aim, I think the same bug is present when the index of a button box is changed.
--> Bug 1/2 are more fundamental problems.

**Comment by tblanke** [comment]
Hi  @wouterpeere ,

I have solved Bug 3 and 4.
The first bugs are due to the fact, that add_2_show ist used multiple times for the same option. So the GUI does not now whicht one is relevant. So Disblay if one is true or do both have to be true?

- [ ] Bug 1
- [ ] Bug 2
- [ ] Bug 3
- [ ] Bug 4

With best regards
 @tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

I think we can move Bug 1 and 2 to your separate issue #84 .

I noticed another bug related to Bug 4:

1. Delete backup
2. Click on add
3. Textbox 'only visible on add' is visible (correct)
4. Increment a above 5 so the subtract aim is disabled
5. 'only visible on add' is hidden (incorrect)

Best,
@wouterpeere

**Comment by wouterpeere** [comment]
Hi @tblanke 

I solved the problem below.

However, none of this seems to work related to the aims of the toggle behaviour is disabled ...

Best,
@wouterpeere

**Comment by tblanke** [comment]
I have fixed it also if the toggle behaviour is disabled.
