### ISSUE TITLE
Disable scrolling in IntBox en FloatBox

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#54]
Currently, when you hover over an IntBox or FloatBox whilste scrolling, you change its value. This can lead to some mistakes in inputs that are sometimes hard to find.

I think it would be better if
1. this 'scrolling' behaviour is just active when the specific option is selected and not just while hovering over
2. you can disable it by setting an attribute to False in the IntBox and FloatBox class

**Comment by tblanke** [comment]
Hi @wouterpeere 

I have implemented a different approach. There is it just scrolled if the box is selected.

**Comment by wouterpeere** [comment]
Hi @tblanke 

Perfect solution!

**Comment by tblanke** [comment]
Great then I will merge it and close this issue.
