### ISSUE TITLE
No background color when saving the GUI figures

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#58]
Hi @tblanke 

I received a question from a GHEtool user. He was wondering if it is possible to save the generated figures from the GUI without the background color of the GUI. I saw that this is also not yet implemented within ScenarioGUI.

I included an example below. I think this would be a good addition, although I do not know if this is even possible, given how the toolbar of the figure works...

Best,
Wouter
![image](https://github.com/tblanke/ScenarioGUI/assets/52632307/a8b388bf-6fae-4e18-9d64-8a3940bb8f92)

**Comment by wouterpeere** [comment]
I did a first attempt at solving this by overwriting the default behaviour of the save button in the NavigationToolbar.
Perhaps you know a more clean/elegant solution for this?

**Comment by tblanke** [comment]
I will take a look at it at the end of the week

**Comment by tblanke** [comment]
Hi @wouterpeere ,

What do you think about setting thebackground color to be transparent? I have uploaded an approach for this. Besides It is possible to save the figure in a editable format like ".svg" and change the background color by hand.

With best regards
@tblanke

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I have implemented the option to customize the colors? Can you please have a look?

With best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

I will go over it tomorrow!

Best,
Wouter

**Comment by wouterpeere** [comment]
Hi @tblanke 

I went over your implementation and I have a couple of remarks/suggestions. I will just list them here and I will try to correct some of them myself later on.


### General remarks
First I wanted to say that it was nice to see the labels translatable! I do not know if this is a feature created in this issue, or it was there before, but this is a nice addition! It would also be nice to have the legend autotranslate in this way. I will create a separate issue for this (issue #65 )

- [ ] Now the option to alter the layout of the figure is always visible. I think it is a good idea to create an attribute in the __init__ of the resultFigure class so people can disable this option.
- [ ] Your solution is way more elaborate than mine, which is fine, but I do think that this offers to much flexibility to some of the users. Perhaps we can implement both, and make an attribute in the __init__ (see comment above) to select either 1) no option should be visible to alter the layout of the plot 2) the plot should be changed automatically when saving (i.e. my implementation) or 3) a fully customizable plot layout (your current implementation). I think we can combine that best of both worlds in this way.

### Buggy behaviour
Below, I will discuss some of the bugs I found.

- [ ] The figure size changes when just toggling between using the default layout values or using the custom ones.
- [ ] When you chose to use a custom layout, whenever you toggle back to the default layout, the layout stays the same.
- [ ] 

- [ ]

**Comment by wouterpeere** [comment]
Hi @tblanke 

I have implemented the general changes already. Do you agree with them?

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I am fine with the changes.
I will try to solve the rest. Only thing I can not reproduce is: If you change the layout to your wishes, and you change the language, the layout is resetted to the default layout.

With best regards
@tblanke

**Comment by tblanke** [comment]
I think I have fixed all the Buggy behaviour

**Comment by wouterpeere** [comment]
Hi @tblanke 

W.r.t. the buggy behaviour of the language change, it was just the switching of pages that caused this issue.
Follow the steps below to find two bugs.
1) Delete the backup file
2) Select 'plot' and run the calculation
3) At the third plot, toggle between yes-no-yes for the default layout (the layout already changes - extra bug).
4) Select no, and change for example the background color
5) Select back the default layout (the layout changes indeed back to the same layout at step 3)
6) Switch to the settings page and back --> the layout will be changed again (existing bug)

**Comment by tblanke** [comment]
Hi @wouterpeere 

I think this should be fixed now.

**Comment by wouterpeere** [comment]
Hi @tblanke 

Perfect! I confirm that it is fixed!
