### ISSUE TITLE
Logs/message only partly visible

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#59]
Hi @tblanke 

I noticed that, whenever we have a long error/warning message, it is only partly shown (even is there is a lot of room available). It would be good if we can have the message text wrap.

See example: 
![image](https://github.com/tblanke/ScenarioGUI/assets/52632307/e9d68deb-b8c8-4cc2-ab27-956eabaded7b)

**Comment by tblanke** [comment]
I have made a first draft to fix it. Can you please have a look?

**Comment by wouterpeere** [comment]
It looks perfect to me!
