### ISSUE TITLE
Make legend translatable

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#65]
Hi @tblanke 

As mentioned in issue #58 it would be great if we can also have the legend of the figures translatable.
This is however not that urgent, for the navigation toolbar makes this also possible (although, not automatically).

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

The legend text is now translateable. Can you please have look?

with best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

This seems to be working fine!
I just added another plot with two lines, so the functionality on how to create a translatable legend is more clear!

Best,
@wouterpeere
