### ISSUE TITLE
Implement multiprocessing next to multithreading

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#68]
Hi @tblanke 

Currently, ScenarioGUI allows for running the calculation of multiple scenario's in different threads. However, python does not (really) support multi-core multithreading. I guess the time saved for GHEtool running the GUI in multithreading, is rather small, since our running time is CPU bound (especially pygfunction) and not I/O bound, where multithreading shines.

Perhaps it can be usefull to implement multiprocessing instead (or next to) multithreading also?

I found some useful background information in this article: https://towardsdatascience.com/multithreading-multiprocessing-python-180d0975ab29
And also in this article: https://towardsdatascience.com/demystifying-python-multiprocessing-and-multithreading-9b62f9875a27

But in the end, I think the choise of multithreading/multiprocessing should be a choise the developer makes when creating a GUI and not the user that uses the GUI (and does not know what the difference between those two is). Therefore, perhaps it is good to remove the 'number of threads' option from the settings page and set them as a variable somewhere when developing the GUI.

What do you think?
Did you run some tests already to measure the speed improvements of multithreading?

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I have implemented an apporach to use Multiprocessing. I would like to stay with the number od threads as a variable so the user can decide how many processes should run in parallel.

With best regards
 @tblanke

**Comment by tblanke** [comment]
Hi @wouterpeere 

Can you please take a look at the multiprocessing approach in the pull request?
If you are fine with it as well I will merge it.

With best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

I think this is fine. I will have to see it within GHEtool to see if it really makes that much of a difference.
No buggy behaviour noticed so far! (Except for example #97 )

Best regards,
@wouterpeere
