### ISSUE TITLE
Flexible amount does not save

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#69]
Hi @tblanke 

I noticed a bug w.r.t. the flexible amount option. This does not seem to save ...

To replicate:
1) delete backup
2) open ScenarioGUI
3) select plot
4) change the name of the first layer
5) save this file
6) close ScenarioGUI
7) open Scenario GUI
--> the name will be resetted to 'layer 1'

Best regards,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I think it is fixed now. Can you please have a look?

With best regards
@tblanke
