### ISSUE TITLE
Bug in loading data of invisible elements

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#72]
Hi @tblanke 

I noticed a really small bug.
I changed the start_gui.py file in the relevant branch, so you can reproduce the error.

1) Remove backup and start the gui
2) Go to plot
3) Alter the value of the  buttonbox 'a or b'
4) Click on substract
5) Save the document
6) Open the document
7) Click on 'plot' and notice that the value of the buttonbox is the default one.

Now, if you follow the nexts steps, it does work
1) Remove backup and start the gui
2) Go to plot
3) Alter the value of the  buttonbox 'a or b'
4) Click on substract
5) Create a new scenario (does not matter what you put here)
6) Save the document
7) Open the document
8) Click on scenario 2 and back to scenario 1
9) Click on 'plot' and notice that the value of the buttonbox is the default one.

Best regards,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I have implemented an approach to enable and disable this behaviour. If this is wishable.

With best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

This works for me!

Best,
@wouterpeere
