### ISSUE TITLE
Problem with autosaving?

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#74]
Hi @tblanke 

I think there is a problem somewhere when the autosaving is active.
I will investigate this further on Monday and will keep you posted in this issue. If there indeed is a problem, perhaps it is a good idea to also fix this before releasing version v0.3.0.

Best,
@wouterpeere

**Comment by wouterpeere** [comment]
Hi @tblanke 

I cannot reproduce these errors in ScenarioGUI themselves, but they are present in GHEtool, but that uses v0.2.2. Perhaps the problems are solved in the meanwhile?

Perhaps we keep this issue open for a little longer to be sure.

Best,
@wouterpeere

**Comment by wouterpeere** [comment]
Hi @tblanke 

Thanks, I will check it!

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

There was an issue with the settings functions. I have solved this and will merge the branch.

With best regards
@tblanke
