### ISSUE TITLE
Implement 'loading' flag in gui_structure

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#79]
Hi @tblanke 

Currently, GHEtool prompts a lot of logs with errors and warnings during the loading of the gui (example: 'no file selected'). This is due to the fact that loading evokes all the 'change_events'.

I was thinking of creating a 'flag' (albeit an variable) in the gui_structure class that gets changed from False to True whenever the gui is loaded? Like the started variable in combine_gui_window.

I will try something out.

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

Good idea.
I confirm that it works and will merge it into the main branch.

With best regards
@tblanke

**Comment by wouterpeere** [comment]
I just changed a couple of things:
1) I disabled the logging in the terminal (otherwise it messes with GHEtool, for messages are logged twice).
2) I added another extra flag, besides the self.started for the case when functions in the gui_structure should be disabled whilst loading a file (so not only whilst starting)
