### ISSUE TITLE
create and and or functionality to show options under mutiple conditions

### ISSUE THREAD

**Issue by tblanke** [tblanke/ScenarioGUI#84]

**Comment by tblanke** [comment]
Bug 1

    Delete backup
    Open the GUI
    Filenamebox is hidden (which is correct, since it depends on the aim-page and the index=1 of the button box ('b'))
    Click on substract
    Click on add again
    --> filenamebox is shown (which is wrong)

Bug 2

    Delete backup
    Open the GUI
    Filenamebox is hidden (which is correct, since it depends on the aim-page and the index=1 of the button box ('b'))
    Click on substract
    Click on 'b' in the buttonbox
    The filenamebox is visible (although not on the aim add page!)

**Comment by tblanke** [comment]
I think we can move Bug 1 and 2 to your separate issue https://github.com/tblanke/ScenarioGUI/issues/84 .

I noticed another bug related to Bug 4:

    Delete backup
    Click on add
    Textbox 'only visible on add' is visible (correct)
    Increment a above 5 so the subtract aim is disabled
    'only visible on add' is hidden (incorrect)

**Comment by wouterpeere** [comment]
> I think we can move Bug 1 and 2 to your separate issue #84 .
> 
> I noticed another bug related to Bug 4:
> 
> ```
> Delete backup
> Click on add
> Textbox 'only visible on add' is visible (correct)
> Increment a above 5 so the subtract aim is disabled
> 'only visible on add' is hidden (incorrect)
> ```

@tblanke , this has, if I see it correctly, nothing to do with this issue, since this 'only visible on add' textbox has only 1 dependency to be shown. I therefore reopened the previous issue and proposed a solution.

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi  @wouterpeere ,

I have implemented a show_option_under_multiple_conditions with two variables functions_check_for_or for all check for the or condition and functions_check_for_and for the and conditions. They can be used alone or together.
What do you think? Is this a suitable solution?

With best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

I was a little bit confused on how the check_for_and and check_for_or can be combined, because there is also logic between them. Because, if you use both, and the check_for_and conditions are not True, the check_for_or conditions are irrelevant, since there exists an 'and' relationship between both.

Now, I was thinking: what we are trying to do, is basically mimicking the behaviour of logical operators, which are implemented in python already. I think that: 'check_for_and' and 'check_for_or' are fine, separately, but I would add a third option: 'check_for_logic' where you can enter the logical yourself.

E.g. what you have implemented now at line: 299 of start_gui.py can be expressed logically as:
```python
(self.aim_plot.widget.isChecked or partial(self.int_small_1.check_linked_value, (None, 20))) and partial(self.int_small_2.check_linked_value, (26, None))
```
If you check for the truth value of the statement above, you get exactly the behaviour you want.

**Comment by wouterpeere** [comment]
Hi @tblanke 

I already implemented 1 and 2 (tests will follow).
What do you think? In my opinion, this is way more transparent.


Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I will take a look at this next week.

With best regards
@tblanke

**Comment by tblanke** [comment]
Hi @wouterpeere ,

wtr. 4) Should the check of the option just be evaluated if it is visible or should the linked option just be checked for its value if it is visible?
wtr. 7) I don not see an solution for this. Your consern is that an option A is changing a value on option B which is changing an value on option A and so an right? I think this is something the user has to be aware of.
wtr. 8) I agree with the visibilityChanged event. Do you think we should create an extra function to check both? like change_event_incl_show

**Comment by wouterpeere** [comment]
Hi @tblanke 

W.r.t. 4) Interesting distinction. My question was related to the second: what if a linked option is invisible: what do we do with its 'truth value'. I think if the option itself is invisible (i.e. the first part in your sentence), the check should not be evaluated. I think we can discuss this vague terminology in our next meeting?
W.r.t 7) I agree.
W.r.t. 8) I think extra functions will make anything more complex. Perhaps we can change the change_event function to include an optional parameter 'incl_show'? so we have change_even(function_2_be_called, include_visibility) or something like that?

Best,
@wouterpeere
