### ISSUE TITLE
Combine two ScenarioGUI documents

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#88]
Hi @tblanke 

I thought it would be a nice feature if a user can combine two documents. This would normally be not that hard to implement, since the saved format is json, so it should be easy to combine.

Here are some of the steps I think should be taken to implement this feature.

- [x] Create function to combine two saved docs. I think we best make this as general as possible, since other users of ScenarioGUI can save other things in the json-format as well (or less). For example some users perhaps do not save the results in their document, so the 'combine_two_docs' function should be able to handle this.
- [x] Create button 'import other document' in the to bar to import another document.
- [x] Create test to check this feature.

Best
@wouterpeere

**Comment by wouterpeere** [comment]
Hi @tblanke 

I am reviewing this.
Something I noticed already that importing a *.txt file seems to be broken? Exporting works fine, but importing gives an error at line 301 of start_gui.py. 'TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'indent''

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I have fixed this issues.

With best regards
@tblanke
