### ISSUE TITLE
Import other, none ScenarioGUI, documents

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#89]
Hi @tblanke 

I refer to this, w.r.t. https://github.com/wouterpeere/GHEtool/issues/85.

In order for this to work, ScenarioGUI should allow for more extensions to be loaded (so this list of extensions should somewhere be a list). The extensions that are not of 'ScenarioGUI' itself, should be passed through a function to convert it to a suitable document for the ScenarioGUI before loaded. I think this is a functionality that should best be implemented here, albeit in a general way.

Steps I think should be taken:
- [x] Create a list of all extensions that can be loaded, next to the extension linked to the ScenarioGUI itself.
- [x] Create a general function that takes a callable object for each extension *.abc, that converts a file of *.abc to the ScenarioGUI format.
- [x] Test to check this behaviour.

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I have implemented a first approach. Can you please take a look?

With best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

I think your solution is very elegant!

I will open the PR for you.

Best,
@wouterpeere
