### ISSUE TITLE
Figure becomes bigger and bigger

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#96]
Hi @tblanke 

I noticed another bug.

To replicate:

1. Delete backup
2. Create scenario and press calculate
3. Click on settings
4. Click on results
5. --> the figure will be larger and will keep increasing in size if you toggle between settings and results further.

Best,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I can not really reproduce this issue. There is an maybe fix uploaded. Can you try if this solves the issue?

With best regards
@tblanke

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I still can not reproduce this. The size it not changing even after 20 times toggeling. Do you have installed the newest package versions?

With best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

Yes, I have updated all the requirements. However, I notice I only get this behaviour for the aim 'add' not for the aim 'plot'.
Did you try the above steps for the 'add' aim?

Best,
@wouterpeere

**Comment by wouterpeere** [comment]
This is really strange ... Can we schedule a very short meeting to discuss/show this problem?

**Comment by wouterpeere** [comment]
Hi @tblanke 

I think we are almost there with this issue. Currently, whenever resizing the window, the figures get smaller (which is good), however the scrolling behaviour is changed. If you make the height of the window smaller, the figure shrinks, but the scrolling speed when hovering over the figures becomes larger, which is rather annoying ...

Best,
@wouterpeere

**Comment by tblanke** [comment]
I think I have found a solution. Can you please take a look?

**Comment by wouterpeere** [comment]
Perfect! What an elegant solution this is ...
