### ISSUE TITLE
Inconsistent Figure layout

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#97]
Hi @tblanke 

I noticed some annoying behaviour with the figure layout.
To replicate (I used issue 96 branch, but I think present in all branches):

1. Remove backup
2. Create a scenario and press calculate. The figure has a certain layout (I cannot even post a picture, because every time I do it again, the label format changes).
3. Save the file and close ScenarioGUI
4. Open Scenario GUI
5. Press results --> The label layout is changed
6. Close Scenario GUI
7. --> repeat 4 5 6 and notice that the layout is always different.

Another thing I noticed: 

1. Remove backup
2. Open ScenarioGUI and press calculate current scenario and notice the layout of the labels
3. Close ScenarioGUI without saving
4. Repeat 2 and 3 and every time the figure has another label layout

Best regards,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I have uploaded a fix. Can you please have a look?

With best regards 
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

This seems to work!

Best regards,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I will take a look at this next week.

With best regards
@tblanke

**Comment by wouterpeere** [comment]
I thinks this issue is solved!
