### ISSUE TITLE
Changing aims is not noticed (only issue 96 branch)

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#98]
Hi @tblanke 

I noticed another bug in the issue96 branch, which is not there in the main branch, but I do not want it to be merged with this bug. To reproduce:

1. Delete backup
2. Open ScenarioGUI and click two times on add scenario
3. Calculate all scenario's
4. Change the aim of scenario 2 to plot --> notice how this does not leave a (*) at the end of the scenario
5. Click on scenario 1
6. Click on scenario 2 --> back to 'add' aim __(bug 1)__
7. Change the aim of scenario 2 back to plot
8. Press calculate --> the correct results are shown for the 'plot' aim
9. Click on scenario 1 and back to scenario 2 --> the results are changed to that of the 'add' aim

Best regards,
@wouterpeere

**Comment by wouterpeere** [comment]
It is also the case that, (instead of moving to step 5) if you click on results, the results will not have changed even though the aim changed.

**Comment by tblanke** [comment]
This is already fixed in the main branch
